services:
  - type: web
    name: gsm-transport-app
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: "3002"
    secrets:
      - key: SERVICE_ACCOUNT_JSON
      - key: ADMIN_TOKEN
      - key: CHROME_PATH
